version: "3.8"
services:
  clickhouse_ndc:
    build:
      context: .
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
    volumes:
      - ./generated_config.json:/ndc-config.json
    command: serve --port 4000 --configuration /ndc-config.json
