[package]
name = "ndc-clickhouse"
version.workspace = true
edition.workspace = true

[dependencies]
ndc-sdk = { workspace = true }
ndc-clickhouse-core = { path = "../ndc-clickhouse-core" }
tokio = "1.36.0"
